### PR TITLE
Create bug_template.md

### PR DESCRIPTION
**Pull request by lenkis**
A template for reporting bugs; to be linked from https://tarantool.io/en/developers/

### CODE REVIEW

**Comment by Totktonada** [comment]
I think it worth to place it in ${REPO}/.github/ISSUE_TEMPLATE.md (consider [1]) to show this text in the new issue form and sync with @sergw, because he has the task to add such text. Alternatively it is possible to place the file to ${REPO}/ISSUE_TEMPLATE.md, but many auxiliary files in a project root is not good, IMHO.

[1]: https://blog.github.com/2016-02-17-issue-and-pull-request-templates/

**Comment by lenkis** [comment]
Тикет ты закрыл, а темплейт для создания тикетов в репозиторий тарантула не
подтянулся.
Кого поклевать с этим?

**Comment by Totktonada** [comment]
@lenkis Перенеси в файл .github/ISSUE_TEMPLATE.md, открой новый PR в master.

**Comment by lenkis** [comment]
Please help to commit this file to the default repo branch:
https://github.com/tarantool/tarantool/commit/0a1744c41e4dc8d1977c88153812f4e58c1236eb#diff-1a1c3dd142f76a5fad803a0c52839881

**Pull request closed without merging**
