### PR TITLE
update and delete by secondary unique index

### LINKED ISSUE #943: UPDATE by non-primary index
Documentation on [IProto Protocol](http://tarantool.org/doc/dev_guide/box-protocol.html) states, that UPDATE accepts field 0x11 - `INDEX_ID` .

But in reality this field is ignored (and could be even missed), and key is always assumed to be primary key.

If `INDEX_ID` is not part of a protocol, then documentation should be fixed. If it is "reserved for future usage", then at least it should be checked for equality to primary index.

### PR DESCRIPTION
**Pull request by funny-falcon**
fix #943 - update and delete by secondary unique index

### CODE REVIEW

**Comment by funny-falcon** [comment]
looks like "index:update" and "index:delete" is not documented.

**Comment by kostja** [comment]
The patch is merged into 1.6.6 (1.6 branch)

**Comment by funny-falcon** [comment]
What with master? will it be solved in other way? or some other decision will be chosen about updating by secondary index?

**Comment by kostja** [comment]
The master is heavily used in production and featue frozen. 1.6.6 will
mature in a couple of months.

**Pull request closed without merging**
