### PR TITLE
Added support for various HMACs to 'crypto' module.

### PR DESCRIPTION
**Pull request by amdei**
This PR adding various kind of HMAC (hash-based keyed MAC) to build-in 'crypto' module
HMAC-SHA256 is especially important for AWS V4 auth.

Prerequisites: OpenSSL 1.0.0+

Sample usage:

    crypto = require('crypto')
    crypto.hmac.sha1('012345678', 'fred')

    -- Incremental update:
    local key = '111xxx'
    hmac_sha1 = crypto.hmac.sha1.new(key)
    hmac_sha1:update('abc')
    hmac_sha1:update('cde')
    hmac_sha1:result()

See more examples in crypto_hmac.test.lua file.
Comments and suggestions are welcome!

### CODE REVIEW

**Comment by rtsisyk** [comment]
This pull requests looks OK for me. 
I rebased it, fixed trailing space, removed duplicate code and pushed to `hmac` branch. 
@GeorgyKirichenko will make the second review today.

**Comment by rtsisyk** [comment]
#725 has been moved to 1.7.4 milestone.

**Comment by rtsisyk** [comment]
Your patch is OK. However, there is some controversy in the team about our built-in **[crypto](https://tarantool.org/doc/reference/reference_lua/crypto.html) module. A very similar patch for HMAC was implemented half a year ago, but we decided to discard it and use **[luaossl](https://github.com/tarantool/luaossl)** instead. The reason was obvious - OpenSSL has tons of ciphers, digests, encryption/decryption algorithms, etc. Wrapping all these features and re-implementing **luaossl** is a cost we can't afford.

@amdei, could you please take a look on [**luaossl**](http://www.25thandclement.com/~william/projects/luaossl.pdf)? Shall we implement our own **luaossl** or it is better to go abandon our **[crypto](https://tarantool.org/doc/reference/reference_lua/crypto.html)** module and go with **luaossl** instead? I see that you are from cryptopro.ru, so I need definitely to take your feedback on this topic into account ;) 

@wahern and @daurnimator, what do you think about it?

**Comment by daurnimator** [comment]
> @wahern and @daurnimator, what do you think about it?

The API is similar (but not totally the same) as luaossl's "openssl.hmac" module.

As you note: luaossl does offer most of the functionality that OpenSSL is capable of, I'm not sure why you would choose to maintain your own implementation vs using luaossl's: but that is up to you.


> .... especially important for AWS V4 auth.

Oh? I'm curious what you might be doing with AWSv4 auth.
I was recently looking into implementing/[forking](https://github.com/chatid/laws) an AWS library for lua (using https://github.com/daurnimator/lua-http) for a few things that use awsv4 including Kinesis and S3.

**Comment by amdei** [comment]
> Shall we implement our own **luaossl** or it is better to abandon our **crypto** module and go with **luaossl** instead?

How do you see future of a **crypto** module? Now its looks like a light-weigth and easy-to-use implementation of basic things (well, except HMACs :-) ), provided out-of-the-box.
For me, as a tarantool user, it is better to have it, instead of using some other heavy monster. Which should be installed and maintained separately, what increase roll-out and maintenance cost.
Thus, as tarantool user, I would stay with simplest possible build-in **crypto** module. It should implement algorithms, not protocols. It has symmetric ciphers, hashes and hmacs. I could not think what else could be added there.
For advanced usage, users could go with **luaossl** or whatever they prefer.

**Comment by rtsisyk** [comment]
We discussed and decided to add this feature on-board to make our users happy. For advanced crypto features please use luaossl instead. 

Pushed as 1.7.3-273-g6cc47f6. Thanks for the patch and your feedback.

**Pull request closed without merging**
