### PR TITLE
box/memtx: support bitset indexes for binary fields

### LINKED ISSUE #5071: feature: Support bitset indexes for binary fields

### PR DESCRIPTION
**Pull request by mary3000**
Closes #5071

### CODE REVIEW

**Comment by PersDep** [comment]
I think @TarantoolBot request is required, at least in tables about indexed field types at pages https://www.tarantool.io/en/doc/latest/book/box/data_model/ and https://www.tarantool.io/en/doc/latest/reference/reference_lua/box_space_index/ it has to be reflected that bitset index now supports varbinary type.

Also almost all new strings in .c files have space indentations now. Tabs should be used.

Otherwise LGTM.

**Comment by PersDep** [comment]
Also this patch needs a @ChangeLog, probably, as a comment, which will be added to release notes. The format should be like the following:
```
@ChangeLog:
 * Composite types extraction is now supported in key_def (gh-4538).
```

**Review by alyapunov — APPROVED** [review]
LGTM

**Comment by mary3000** [comment]
@PersDep added @TarantoolBot and @Changelog infos in the commit message

**Review by PersDep — APPROVED** [review]
LGTM
(Commit message strings should not be longer than 72 though)
Also @ChangeLog shouldn't really be in commit message. It is usually being sent as part of the letter to mailing list. In PR i think it should be a comment.

**Comment by Korablev77** [comment]
Pushed to master, changelog is updated (2.7).

**Pull request closed without merging**
