### PR TITLE
Static build: Export symbols from common libraries for tarantool binary

### LINKED ISSUE #4225: Static build: ZSTD symbols are not exported in tarantool binary
I built a shared library which uses zstd functions. When I require it from statically built tarantool (with `ENABLE_BUNDLED_ZSTD` cmake option), it fails:

```
tarantool> require'tnt-kafka'
---
- error: "builtin/luarocks.loader.lua:129: error loading module 'tnt-kafka.tntkafka'
    from file '/.rocks/lib/tarantool/tnt-kafka/tntkafka.so':\n\t/.rocks/lib/tarantool/tnt-kafka/tntkafka.so:
    undefined symbol: ZSTD_compressStream"
...
```
since that symbols are not exported in tarantool executable:
```
[root@f129b479b26c /]# nm -g /build/tarantool | grep ZSTD_compressStream
0000000000be8da0 T ZSTD_compressStream
0000000000be8900 T ZSTD_compressStream_generic
```

### PR DESCRIPTION
**Pull request by RunsFor**
This commit exports symbols from some libraries such as:

- cyrus sasl
- zlib
- zzip
- lz4
- zstd

This is usefull for a static build so there is no need for all those
modules from tarantool ecosystem which would build statically
to link these dependencies inside itself.

To be able to export ZSTD symbols correctly, it is necessary to first
    build zstd and then start cmake where "mkexports" machinery export all
    static libs symbols.

Fixes #4225

### CODE REVIEW

**Comment by RunsFor** [comment]
Right now this PR is blocked by #4245

**Comment by GeorgyKirichenko** [comment]
I do not have any complaints except this one: do we really need this libraries to be exported by default?

**Comment by Totktonada** [comment]
I don't look deeply into the patch, but I don't think we should build a library into tarantool when it is not used in tarantool, but used in one of external modules. I see you link librdkafka into the module: https://github.com/tarantool/kafka/pull/5 This is the right way to do static build.

**Comment by Totktonada** [comment]
To make my point more clear:

* If a library is a direct dependency of tarantool, then I think we can export them from our executable (in case of a static build). Don't sure whether we can declare them as part of our public API: what will going on if some library update will remove a symbol?
* If a library is indirect dependency of tarantool, then I don't sure. ABI compatibility can be changed, a dependency can even gone at all with some update of our direct deps.
* If a library is not our dependency, then we should not link it statically into a tarantool executable at all. If a module requires it, then link it into the module.

See also #2971.

**Comment by kostja** [comment]
The patch is controversial. Please write a description of what you're trying to accomplish first: perhaps it should be done as a cmake option for static build, not as a default behaviour. Then resubmit the pull request (or better send the patch to patches@).

**Pull request closed without merging**
