### PR TITLE
github-ci: add ubuntu groovy (20.10) workflow

### PR DESCRIPTION
**Pull request by VitaliyaIoffe**
Add ubuntu-groovy workflow, which runs on push and pull-requests.

Part of: #5824

### CODE REVIEW

**Comment by Totktonada** [comment]
I pushed https://github.com/packpack/packpack-docker-images/pull/76 and restarted the ubuntu_20_10 job here.

Don't forget to update distros list in tools/update_repo.sh. See 78c1de32b5ee7365751254ab6951f38e12d34c29 for example.

> Part of: #5824

Is there anything else you plan to do within this task? I think, the task can be closed from this PR.

Don't forget to notify tarantool/rws maintainer (@LeonidVas) about the new distro. Let's agree with him, how exactly: issue, PR or somehow else.

There are A LOT of globbing-patterns-out-of-order warnings. There no such warnings in ubuntu_20_04 job: it is something new. Please, look what is wrong. I suggest to glance on PR #5256.

**Comment by LeonidVas** [comment]
> Don't forget to notify tarantool/rws maintainer (@LeonidVas) about the new distro. Let's agree with him, how exactly: issue, PR or somehow else.

I was notified.

**Review by Totktonada — APPROVED** [review]
LGTM.

I suggest to add update_repo fix first, then add the new CI workflow (or squash those commit). This way every commit will be buildable / deployable. However I don't insist here.

**Comment by Totktonada** [comment]
Fails in CI should not be relevant, but it would be good to know, whether they're known and whether there are plans to fix them in a near future.

**Comment by Totktonada** [comment]
BTW, I would rebase on top of current master just in case: there were considerable amount of changes since you sent the series to review.

**Review by kyukhin — APPROVED** [review]

**Comment by Totktonada** [comment]
We forgot to backport it to 1.10, so I made it now: 1.10.11-20-gf82131a96.

**Pull request merged**
