### PR TITLE
cmake: fix build with GCC's AddressSanitizer

### PR DESCRIPTION
**Pull request by ligurio**
GNU GCC compiler has AddressSanitizer support since 4.8.0 [1], but it was unsupported in tarantool's build. The patch fixes a build by GNU GCC with enabled AddressSanitizer.

1. https://gcc.gnu.org/gcc-4.8/changes.html

NO_CHANGELOG=build
NO_DOC=build
NO_TEST=build

### CODE REVIEW

**Review by grafin — APPROVED** [review]
Thanks for the patch! LGTM, I've checked it with gcc 13.3.0, it works. Would be great if you could fix UBSAN for gcc too).

Currently it fails with:

```
CMake Error at cmake/compiler.cmake:228 (message):
  Undefined behaviour sanitizer only available for clang
Call Stack (most recent call first):
  src/CMakeLists.txt:4 (enable_tnt_compile_flags)
```

But as far as I googled - UBSAN works with gcc starting with version 4.9.x.

**Comment by ligurio** [comment]
> Thanks for the patch! LGTM, I've checked it with gcc 13.3.0, it works. Would be great if you could fix UBSAN for gcc too).

Sure, I'll do the same for UBSan but later and in another PR (in scope of #10228 and after merging of #10605).

**Review by Buristan — COMMENTED** [review]
Hi, Sergey!
Thanks for the patch!
LGTM with the one question below:

I see the following lines regarding static build and Clang 16:
https://github.com/tarantool/tarantool/blob/47295fdebc1910b990c391c26fe92918a9c0c001/cmake/CheckDependencies.cmake#L33-L36

Are they Clang-specific, or should we update them for static build with GCC too?

**Comment by ligurio** [comment]
> Are they Clang-specific, or should we update them for static build with GCC too?

No, seems `libresolv` is not needed. But `libasan` must be added to `ALLOWLIST`:

```diff
--- a/cmake/CheckDependencies.cmake
+++ b/cmake/CheckDependencies.cmake
@@ -34,6 +34,9 @@ elseif(UNIX)
     if(CMAKE_CXX_COMPILER_ID STREQUAL "Clang" AND ENABLE_ASAN)
         set(ALLOWLIST ${ALLOWLIST} libresolv)
     endif()
+    if(CMAKE_CXX_COMPILER_ID STREQUAL "GNU" AND ENABLE_ASAN)
+        set(ALLOWLIST ${ALLOWLIST} libasan)
+    endif()
 else()
     message(FATAL_ERROR "Unknown platform")
 endif()
```

Otherwise build has failed.

**Review by Buristan — APPROVED** [review]
Thanks for the updates!
LGTM!

**Pull request merged**
