### PR TITLE
Add option for disable follow location behavior

### PR DESCRIPTION
**Pull request by norguhtar**
@TarantoolBot document
Title: 'follow_location' http.client option
It allows disable follow location behavior used by default by set 0
For additional info see https://curl.haxx.se/libcurl/c/CURLOPT_FOLLOWLOCATION.html

### CODE REVIEW

**Comment by norguhtar** [comment]
Motivation for this change. Some times you need put variables in request before follow location header.

**Comment by Totktonada** [comment]
Rebased on top of the current master, changed the option type to boolean, moved the code to keep the same order everywhere, added a test, rephrased comments and the commit message a bit.

**Comment by Totktonada** [comment]
@kyukhin Please, proceed.

**Comment by Totktonada** [comment]
Updated also option descriptions in httpc.lua.

**Comment by Totktonada** [comment]
Rebased on the current master.

**Pull request merged**
