### PR TITLE
Add option interface for set source interface in http client

### PR DESCRIPTION
**Pull request by norguhtar**
I'm add option for set source interface in http client. Can you add this in upstream?

### CODE REVIEW

**Comment by Totktonada** [comment]
``@TarantoolBot document`` is verbatim text. Kinda that:

```
@TarantoolBot document
Title: 'interface' http.client option
It allows to set a network interface for an outgoing
connection using the interface name or IP address.
See https://curl.haxx.se/libcurl/c/CURLOPT_INTERFACE.html
```

**Comment by norguhtar** [comment]
Оk. thanks

**Comment by norguhtar** [comment]
Done.

**Comment by Totktonada** [comment]
@kyukhin Please, proceed.

**Pull request merged**
