### PR TITLE
rocks: switch luarocks module to 3.1.3 branch

### PR DESCRIPTION
**Pull request by 0x501D**
Part of https://github.com/tarantool/security/issues/12

NO_DOC=bugfix
NO_TEST=bugfix
NO_CHANGELOG=bugfix

### CODE REVIEW

**Review by LeonidVas — COMMENTED** [review]
Hi! Thank you for the patch.
I think it is better to use title like: "rocks: bump 3.1.3 version". Because it does not matter how we do it (switch the branch, update the master...).
Add to the commit body the reason of bumping new version.

**Comment by 0x501D** [comment]
Commit message is fixed.

**Comment by Totktonada** [comment]
What I see on a brief glance:

https://github.com/tarantool/luarocks/commit/50ac6c4ee2fc84d6eccb13ef0f2994193f8e6b80 was dropped from our patchset, because it is part of upstream's v3.1.3 (https://github.com/luarocks/luarocks/pull/1012). Looks ok.

https://github.com/tarantool/luarocks/commit/84f2977ec4596bd7512c93b267434b21a5daf282 was dropped from our patchset. It is likely, because this code was reworked in the upstream (https://github.com/luarocks/luarocks/pull/1026) and don't concatenate `nil` with strings anymore. It also seems that the original problem can't appear due to the following patch from our patchset: https://github.com/tarantool/luarocks/commit/d4b092396ae17035ec9f0ada90e4ac9d9b9dad51 (see also comments in https://github.com/tarantool/luarocks/pull/7, search for 'fix check default lua_version'). Looks ok.

https://github.com/tarantool/luarocks/commit/22de580f65b2e52a91dad19904d3955e6dff7414 was added to our patchset. It is about the strict mode, so I would squash it to the first commit ('Made luarocks compatible with tarantool'), where we fix all other strict mode problems. Looks ok aside of the nit.

I don't know, whether other patches were changed somehow or not, whether they apply clean on the new version.

I don't know what testing was performed to ensure that everything works. (You can consider my [log](https://github.com/tarantool/luarocks/pull/7#issuecomment-502472853) of manual `tarantoolctl rocks` testing.)

In a guess that all other patches applies cleanly or requires only obvious changes and that adequate manual testing was performed, I have no objections here.

**Review by Totktonada — APPROVED** [review]

**Comment by 0x501D** [comment]
Commit was squashed, `tarantoolctl` rocks was tested with your checklist.

**Review by LeonidVas — APPROVED** [review]
LGTM

**Review by LeonidVas — APPROVED** [review]
LGTM

**Pull request merged**
