### PR TITLE
Stabilize Lua benches

### PR DESCRIPTION
**Pull request by Buristan**
This patchset makes Lua benchmars more stable:
The first commit removes excess JIT settings from <lua/uri_escape_unescape.lua> and increases the amount of iterations for tests.
The second commit disables ASLR to avoid different LuaJIT VM states from run to run.

### CODE REVIEW

**Review by Totktonada — APPROVED** [review]
No objections from my side.

**Comment by ligurio** [comment]
Results with two consequent runs:

image

**Comment by ligurio** [comment]
I've executed benchmarks several times to evaluate the effect made by commits to a stable results.

| N | changes | `uri.unescape()`  | `uri.escape()` | Job |
| ---| -------------| ------------- | ------------- | -------------------------
| 1  | both commits (1st run)  |  9406  | 4161  | [URL](https://github.com/tarantool/tarantool/actions/runs/12049062423/job/33595027936?pr=10863)
| 2  | both commits (2nd run) | 9411  | 4246  | [URL](https://github.com/tarantool/tarantool/actions/runs/12049432124/job/33596165914?pr=10863)
| 3  | both commits (3rd run) | 9341  | 4111  | [URL](https://github.com/tarantool/tarantool/actions/runs/12049750239/job/33597155212?pr=10863)
| 4  | both commits (4th run)  | 9395  | 4153  | [URL](https://github.com/tarantool/tarantool/actions/runs/12050084205/job/33598214099?pr=10863)
| 5  | both commits (5th run) | 9199   | 4161  | [URL](https://github.com/tarantool/tarantool/actions/runs/12050483965/job/33599464838?pr=10863)
| 6  | both commits (6th run)  |  9234  | 4174  | [URL](https://github.com/tarantool/tarantool/actions/runs/12050841272/job/33600560395?pr=10863)
| 7  | master + "perf: disable ASLR for perf testing" (1st run) |  6555  | 4391  | [URL](https://github.com/tarantool/tarantool/actions/runs/12051193954/job/33601690766?pr=10863)
| 8  | master + "perf: disable ASLR for perf testing" (2nd run) | 6815  | 4661  | [URL](https://github.com/tarantool/tarantool/actions/runs/12051578550/job/33602926812?pr=10863)
| 9  | master + "perf: disable ASLR for perf testing" (3rd run) | 6652  | 4502  | [URL](https://github.com/tarantool/tarantool/actions/runs/12052273185/job/33605210121?pr=10863)
| 10  | master + "perf: stabilize <lua/uri_escape_unescape.lua>"  (1st run)  |  8240 | 4300  | [URL](https://github.com/tarantool/tarantool/actions/runs/12052686937/job/33606575291?pr=10863)
| 11  | master + "perf: stabilize <lua/uri_escape_unescape.lua>" (2nd run) |  7909  |  4201 | [URL](https://github.com/tarantool/tarantool/actions/runs/12053150576/job/33608143242?pr=10863)
| 12 | master + "perf: stabilize <lua/uri_escape_unescape.lua>"  (3rd run)  |  8573  | 4313  | [URL](https://github.com/tarantool/tarantool/actions/runs/12053536672/job/33609444129?pr=10863)

Measurements were done in https://github.com/tarantool/tarantool/pull/10863, branch `ligurio/gh-noticket-stabilize-lua-benches`. Note that commit with disabling ASLR was reverted (runs NN 10, 11 and 12) by the patch below:

```diff
--- a/perf/tools/setup_env.sh
+++ b/perf/tools/setup_env.sh
@@ -107,7 +107,7 @@ set_kernel_setting \
 set_kernel_setting \
   "Disable ASLR" \
   "/proc/sys/kernel/randomize_va_space" \
-  "0"
+  "2"
 
 ###
 # System tuning.
```

screen-1732722939

**Review by ligurio — APPROVED** [review]
LGTM

**Pull request merged**
