### PR TITLE
Introduce macOS ver. 12 testing 

### PR DESCRIPTION
**Pull request by kyukhin**
The patchset introduces testing on macOS version 12.
It does that in the following way:
1. Drop testing of macOS 10.x
2. Move macOS LTO testing to macOS 11 variant
3. Introduce new workflow for macOS 12 testing for amd64 arch (app-tap/popen test was disabled)

### CODE REVIEW

**Review by ylobankov — COMMENTED** [review]
Please drop osx_10_15.yml workflow.

**Review by ylobankov — APPROVED** [review]
LGTM, thanks!

**Comment by Totktonada** [comment]
I looked at the reason of popen test fail, see results [here](https://github.com/tarantool/tarantool/issues/6674#issuecomment-1002848312).

**Comment by kyukhin** [comment]
> I looked at the reason of popen test fail, see results [here](https://github.com/tarantool/tarantool/issues/6674#issuecomment-1002848312).

Great! I've mentioned the issue in the corresponding skipcond file.

**Pull request merged**
