### PR TITLE
swim: fix debug assertion abort in proto decode

### PR DESCRIPTION
**Pull request by SweetVishnya**
assert(cur < end) after mp_load_u8 in mp_check_binl was failing

This PR fixes abort found with libFuzzer target in #6627

### CODE REVIEW

**Review by Gerold103 — CHANGES_REQUESTED** [review]
Thanks for the patch! Please, add a test to `unit/swim_proto.c`. All patches should have a test when possible. Here it should be. Libfuzzer is rather a helper tool than a regular test running on people's machines. Also I can't run it anyway, so I can't formally validate the fix.

**Comment by SweetVishnya** [comment]
I managed to add a regression test.

Output without patch applied:
```
./swim_proto.test

	*** main ***
1..3
	*** swim_test_member_def ***
    1..13
    ok 1 - not map header
    ok 2 - not uint member key
    ok 3 - too big member key
    ok 4 - STATUS is not uint
    ok 5 - invalid STATUS
    ok 6 - invalid address
    ok 7 - bad port
    ok 8 - unexpected buffer end
    ok 9 - unexpected buffer end
    ok 10 - uuid is nil/undefined
    ok 11 - port is 0/undefined
    ok 12 - normal member def
swim_proto.test: /home/vishnya/fwork/tarantool/src/lib/msgpuck/msgpuck.h:2052: ptrdiff_t mp_check_binl(const char *, const char *): Assertion `cur < end' failed.
[1]    17720 abort (core dumped)  ./swim_proto.test
```

Output after patch is applied:
```
./swim_proto.test

	*** main ***
1..3
	*** swim_test_member_def ***
    1..13
    ok 1 - not map header
    ok 2 - not uint member key
    ok 3 - too big member key
    ok 4 - STATUS is not uint
    ok 5 - invalid STATUS
    ok 6 - invalid address
    ok 7 - bad port
    ok 8 - unexpected buffer end
    ok 9 - unexpected buffer end
    ok 10 - uuid is nil/undefined
    ok 11 - port is 0/undefined
    ok 12 - normal member def
    ok 13 - zero length bin
ok 1 - subtests
	*** swim_test_member_def: done ***
	*** swim_test_meta ***
    1..8
    ok 1 - not map header
    ok 2 - not uint meta key
    ok 3 - unknown meta key
    ok 4 - unexpected end
    ok 5 - invalid version
    ok 6 - port is 0/undefined
    ok 7 - version is 0/undefined
    ok 8 - normal meta
ok 2 - subtests
	*** swim_test_meta: done ***
	*** swim_test_route ***
    1..5
    ok 1 - route was expected, but map is too short
    ok 2 - no route map
    ok 3 - empty route map
    ok 4 - zero addresses
    ok 5 - normal route
ok 3 - subtests
	*** swim_test_route: done ***
	*** main: done ***
```

**Review by Gerold103 — CHANGES_REQUESTED** [review]
Thanks for the fixes! Please, merge these 3 commits into one. We usually do fix + test in one commit.

**Comment by SweetVishnya** [comment]
I squashed commits and rebased on master.

**Review by Gerold103 — APPROVED** [review]

**Pull request merged**
