### PR TITLE
Implement xtm API

### LINKED ISSUE #4802: Implement API for H2O-based http server
Now Tarantool has an internal http-server which has several drawbacks:

- Written in lua and works in the TX-thread
- Doesn't support asynchronous http/2. Using of Http 1.x (sync protocol) leads us to create a lot of connections from single client in order to achieve desired number of requests per second.
- cannot serve a lot of connections (more than 2k)
- does not support server pushes / web sockets

After some investigations we have figured out that [H2O](https://github.com/h2o/h2o) is a good candidate to be a new one http-serve with http/2 support.
It supports: 

- multiplexing and async request processing (using frames) 
- server pushes, web sockets
- TLS
- http/2 prioritization

It will be great to test both:

1. COIO implementation
2. implementation using cpipes and cbus

See [H2O as a library](https://h2o.examp1e.net/faq.html#libh2o)

[Link to discussion](https://github.com/tarantool/tarantool/discussions/5641)

### PR DESCRIPTION
**Pull request by EvgenyMekhanik**
Implement API for inter thread communication, based
on lock free spsc queue and example for it.

After XTM repository review need to change .gitmodules here 

Closes #4802

### CODE REVIEW

**Comment by Korablev77** [comment]
Could you extract RFC, format it according to the template and put it near the patch (doc/rfc/). Otherwise, it is merely impossible to understand what is going on...

**Comment by kostja** [comment]
* Evgeny Mekhanik <notifications@github.com> [21/01/20 13:47]:


> Implement API for inter thread communication, based
> on lock free spsc queue and example for it.

lock free is not barrier free.

I'm sceptical the number of memory barriers could be brought to a
lower value than the one produced by the current cbus.

It is possible to reduce interthread communication latency by
using a lock free queue, but I don't see any benefit as long as
each thread is running an event loop.

So what's the point of all this? Some kind of research? 


-- 
Konstantin Osipov, Moscow, Russia

**Comment by mechanik20051988** [comment]
> * Evgeny Mekhanik <notifications@github.com> [21/01/20 13:47]:
> Implement API for inter thread communication, based on lock free spsc queue and example for it.
> lock free is not barrier free. I'm sceptical the number of memory barriers could be brought to a lower value than the one produced by the current cbus. It is possible to reduce interthread communication latency by using a lock free queue, but I don't see any benefit as long as each thread is running an event loop. So what's the point of all this? Some kind of research?
> […](#)
> -- Konstantin Osipov, Moscow, Russia

We are making an API for inter-thread interaction with any event loop in the module. In the case of c bus, we store messages in a queue and deliver them under a mutex at a time at the end of the event loop iteration. In case we don't know which event loop is being used we need to deliver each message individually. It's very slow in case we use mutex.

**Comment by kostja** [comment]
http://docs.libuv.org/en/v1.x/guide/eventloops.html

You should not run h2o in a separate thread, but embed libuv into libev loop.

**Comment by kostja** [comment]
http://docs.libuv.org/en/v1.x/guide/eventloops.html

You should not run h2o in a separate thread, but embed libuv into libev loop.

**Comment by void234** [comment]
> 
> 
> http://docs.libuv.org/en/v1.x/guide/eventloops.html
> 
> You should not run h2o in a separate thread, but embed libuv into libev loop.

Primary user of "xtm" is "httpng" (in development), the whole idea of which is to process TLS/HTTP in separate thread(s).

**Comment by kostja** [comment]
* Sergey Nikiforov <notifications@github.com> [21/02/22 09:30]:
> > 
> > 
> > http://docs.libuv.org/en/v1.x/guide/eventloops.html
> > 
> > You should not run h2o in a separate thread, but embed libuv into libev loop.
> 
> Primary user of "xtm" is "httpng" (in development), the whole idea of which is to process TLS/HTTP in separate thread(s).

h2o is based on libuv. libuv allows embedding into other event
loops. Processing http in a separate thread may make some sense
when you look at a single tarantool instance - this will improve
that instance performance - but makes no sense whatsoever when you
reason in terms of the cluster or even a single server.
How are you going to provision CPU for that thread? Will you pin
an own core?  Isn't it too much? How much memory are you going to
give it, how will it impact the overall instance memory monitoring
and management? If it is not pinned to a core, it becomes naturally
a lower priority than tx thread and jumps from one core to another,
leading to hard-to-track latency spikes and priority inversions.

Even having iproto in its own thread was a dubious choice (an
experiment on my part). Back then there was no good async IO on
Linux, and now there is io_uring.

Going forward it's definitely  a bad idea to use more role threads
- iproto and wal are already under-utilized, so more work should
be shifted into them. Relays should be moved to WAL, vshard should
be moved to iproto, all imaginable network can happen in iproto -
and if anything, we should work on making both WAL and iproto.

-- 
Konstantin Osipov, Moscow, Russia

**Comment by Totktonada** [comment]
What is purpose of this PR? To add the test? If so, it is better to add it right to the xtm repository.

**Comment by EvgenyMekhanik** [comment]
XTM is independent library, it should not be present in tarantool

**Pull request closed without merging**
