### PR TITLE
Instance and cluster configuration schemas

### LINKED ISSUE #8778: Introduce instance and cluster configuration schemas
This issue is part of #8724.

### PR DESCRIPTION
**Pull request by ImeevMA**
This patch-set adds instance and cluster configuration schemas.

Closes #8778

### CODE REVIEW

**Comment by ImeevMA** [comment]
Changes in the last force-push
```Diff
diff --git a/src/box/lua/config/cluster_config.lua b/src/box/lua/config/cluster_config.lua
index b6e712268..71607617a 100644
--- a/src/box/lua/config/cluster_config.lua
+++ b/src/box/lua/config/cluster_config.lua
@@ -74,20 +74,16 @@ local function record_from_fields(fields)
 
             -- Copy fields.
             for kk, vv in pairs(v.fields) do
-                if res.fields[kk] ~= nil then
-                    error(('record_from_fields: duplicate fields ' ..
-                        '%q'):format(kk))
-                end
+                assert(res.fields[kk] == nil, 'record_from_fields: duplicate '..
+                                              'fields '..tostring(kk))
                 res.fields[kk] = vv
             end
 
             -- Copy annotations.
             for kk, vv in pairs(v) do
                 if kk ~= 'fields' and kk ~= 'type' then
-                    if res[kk] ~= nil then
-                        error(('record_from_fields: duplicate annotations ' ..
-                            '%q'):format(kk))
-                    end
+                    assert(res[kk] == nil, 'record_from_fields: duplicate '..
+                                           'annotations '..tostring(kk))
                     res[kk] = vv
                 end
             end
@@ -98,10 +94,8 @@ local function record_from_fields(fields)
             assert(type(k) == 'string')
 
             -- Copy the field.
-            if res.fields[k] ~= nil then
-                error(('record_from_fields: duplicate fields ' ..
-                    '%q'):format(k))
-            end
+            assert(res.fields[k] == nil, 'record_from_fields: duplicate '..
+                                         'fields '..tostring(k))
             res.fields[k] = v
         end
     end
```

**Comment by ImeevMA** [comment]
Diff of the last force-push:
<details>
<summary>Diff</summary>

```Diff
diff --git a/doc/examples/config/credentials.yaml b/doc/examples/config/credentials.yaml
deleted file mode 100644
index f57647a14..000000000
--- a/doc/examples/config/credentials.yaml
+++ /dev/null
@@ -1,115 +0,0 @@
-# Demonstration of the credentials section format.
-#
-# A privilege (rights to do something) may be granted to a role
-# or a user.
-#
-# A privilege is a composition of permissions and objects.
-#
-# {{permissions}}
-# - read
-# - write
-# - execute
-# - create
-# - alter
-# - drop
-# - usage
-# - session
-#
-# {{privilege objects}}
-# - universe
-# - space (NYI)
-# - function (NYI)
-# - sequence (NYI)
-#
-# TODO: Describe permissions appliablity to particular objects.
-#
-# TODO: Explain meaning of 'usage' and 'session' permissions.
-#
-# {{built-in roles}}
-# - public
-# - replication
-# - super
-#
-# TODO: Describe what exactly the built-in roles give.
-#
-# {{built-in users}}
-# - guest
-# - admin
-#
-# TODO: Explain default permissions and password setting for the
-# built-in users.
-
-credentials:
-  roles:
-    # A role that allows direct reading from a space, but requires
-    # to call a function for modifications.
-    api_access:
-      privileges: []
-      # TODO: NYI
-      #- permissions: [read]
-      #  spaces: [myspace]
-      #- permissions: [execute]
-      #  functions: [mufunc]
-
-    # The 'allow everything' role. It is just like the built-in
-    # 'super' role.
-    audit:
-      privileges:
-      - permissions: [read, write, execute, create, alter, drop]
-        universe: true
-
-    # A role can inherit all privileges from a list of given
-    # roles.
-    cdc:
-      roles: [replication]
-
-  users:
-    # A user definition is quite same as a role definition, but
-    # has extra 'password' field.
-    #
-    # Let's create a user for replication.
-    replicator:
-      password:
-        plain: 'topsecret'
-      roles: [replication]
-
-    # Create a user for external clients.
-    client:
-      password:
-        plain: 'secret'
-      # Super is here purely for testing purposes.
-      roles: [api_access, super]
-
-    # Set a password for the built-in admin user.
-    #
-    # The 'admin' user has all the rights by default.
-    admin:
-      password:
-        plain: 'topsecret'
-
-    # A restricted user to call monitoring functions.
-    monitor:
-      password:
-        plain: 'secret'
-      privileges: []
-      # TODO: NYI
-      #- permissions: [execute]
-      #  functions:
-      #  - box.info
-      #  - box.stat
-      #  - metrics.getmetrics
-
-iproto:
-  listen: 'unix/:./{{ instance_name }}.iproto'
-  advertise: 'replicator:topsecret@unix/:./{{ instance_name }}.iproto'
-
-groups:
-  group-001:
-    replicasets:
-      replicaset-001:
-        instances:
-          instance-001:
-            database:
-              rw: true
-          instance-002: {}
-          instance-003: {}
diff --git a/test/config-luatest/cluster_config_schema_test.lua b/test/config-luatest/cluster_config_schema_test.lua
index 786f59191..99f43e432 100644
--- a/test/config-luatest/cluster_config_schema_test.lua
+++ b/test/config-luatest/cluster_config_schema_test.lua
@@ -225,11 +225,3 @@ g.test_example_replicaset = function()
     fh:close()
     cluster_config:validate(config)
 end
-
-g.test_example_credentials = function()
-    local config_file = fio.abspath('doc/examples/config/credentials.yaml')
-    local fh = fio.open(config_file, {'O_RDONLY'})
-    local config = yaml.decode(fh:read())
-    fh:close()
-    cluster_config:validate(config)
-end

```
</details>

**Comment by ImeevMA** [comment]
Changes in the last force-push:
```Diff
diff --git a/doc/examples/config/replicaset.yaml b/doc/examples/config/replicaset.yaml
index ed238d45f..4e286a48d 100644
--- a/doc/examples/config/replicaset.yaml
+++ b/doc/examples/config/replicaset.yaml
@@ -13,8 +13,8 @@ iproto:
   listen: 'unix/:./{{ instance_name }}.iproto'
   advertise: 'replicator:topsecret@unix/:./{{ instance_name }}.iproto'
 
-#log:
-#  to: file
+log:
+ to: file
 
 groups:
   group-001:
```

**Review by Totktonada — APPROVED** [review]
Thanks for the patchset!

I looked over it once again and it seems good for me.

**Pull request merged**
