### PR TITLE
luajit: bump submodule

### LINKED ISSUE #5688: Introduce a CLI flag for LuaJIT to run memprof dump parsing tool
I suddenly realized that this is unconvenient to use a [standalone shell script](https://github.com/tarantool/luajit/blob/tarantool/tools/luajit-parse-memprof) to run [memprof.lua](https://github.com/tarantool/luajit/blob/tarantool/tools/memprof.lua) tool for parsing memory profiler dump. It's even "non-idiomatic" way for LuaJIT, considering bytecode modules and jit.dump machinery. Hence I propose to introduce a specific flag (kinda `-m` or better `-tm` considering mentioned LuaJIT subsystems and its usage) and drop the shell oneliner.

A separate bullet is providing a such flag with Tarantool.

Considering the proposed change I would also mention that  moving `tools` directory nearby `jit` looks better fitting into the original source code layout.

### PR DESCRIPTION
**Pull request by fckxorg**
memprof: introduce cli flag to run dump parser

Closes #5688

NO_DOC=LuaJIT-only change
NO_TEST=LuaJIT submodule bump
NO_CHANGELOG=LuaJIT-only change

### CODE REVIEW

**Review by andreyaksenov — APPROVED** [review]

**Review by ochaplashkin — APPROVED** [review]
LGTM :rocket:

**Review by Buristan — APPROVED** [review]
Hi, Maxim!
Thanks for the patch!
Generally, LGTM, but I suggest using separate commits for the submodule bump and cli flag introduction.

**Review by ligurio — APPROVED** [review]
LGTM

**Comment by ligurio** [comment]
LGTM for LuaJIT part - https://lists.tarantool.org/tarantool-patches/cover.1693481682.git.m.kokryashkin@tarantool.org/T/#t

@fckxorg Max, please rebase commits on master branch to resolve conflicts.

**Comment by igormunkin** [comment]
The changeset is merged to master in scope of #9388, backported to 2.11 and 2.10 in scope of #9389 and #9390 respectively.

**Pull request closed without merging**
