### PR TITLE
readme: fix grammar and punctuation

### PR DESCRIPTION
**Pull request by masterujjval**
NO_DOC=minor changes in README.md
NO_TEST=minor changes in README.md
NO_CHANGELOG=minor changes in README.md

### CODE REVIEW

**Review by andreyaksenov — APPROVED** [review]

**Comment by kyukhin** [comment]
Please, fix CI (you need to extend commit message).

**Comment by masterujjval** [comment]
Please add 'hacktoberfest-accepted' label if this PR got merged.

**Comment by ylobankov** [comment]
Please compose the commit message like below to pass CI and get merged.

```
readme: fix grammar and punctuation

NO_DOC=minor changes in README.md
NO_TEST=minor changes in README.md
NO_CHANGELOG=minor changes in README.md
```

**Comment by masterujjval** [comment]
done

**Comment by masterujjval** [comment]
please add 'hacktoberfest-accepted' label

**Pull request closed without merging**
