### PR TITLE
coro: fix dereferencing of `void *` pointer warning

### LINKED ISSUE #8125: Dereferencing `void *` pointer in libcoro warning
Building Tarantool with GCC diagnoses the following warning:
```console
[2/635] Building C object CMakeFiles/coro.dir/third_party/coro/coro.c.o
/Users/georgiy.lebedev/Work/tarantool/third_party/coro/coro.c: In function 'coro_init':
/Users/georgiy.lebedev/Work/tarantool/third_party/coro/coro.c:127:35: warning: dereferencing 'void *' pointer
  127 |   : "rm" (arg), "rm" (func), "m" (*arg)
      |                                   ^~~~
```

### PR DESCRIPTION
**Pull request by CuriousGeorgiy**
Closes #8125

### CODE REVIEW

**Review by Gumix — APPROVED** [review]
Just for the record, `arg` is actually `NULL` in Tarantool.

**Comment by locker** [comment]
@CuriousGeorgiy Build fails on some old platforms (debian 9, ubuntu 16, centos 7). PTAL.

```
/build/usr/src/debug/tarantool-2.11.0~entrypoint.855.dev/third_party/coro/coro.c:108:3: error: output operand 0 must use ‘&’ constraint
   __asm__ volatile(
   ^
```

**Comment by CuriousGeorgiy** [comment]
@gumix looks like a bug in GCC: if I remove `st` registers from the clobber list, it [compiles](https://godbolt.org/z/785b8d4qY) — if I add any `st` register, it fails to compile.

**Review by locker — APPROVED** [review]

**Comment by sergos** [comment]
Yet the `m` for the `*arg` was an excess, since you had no access through the pointer

**Review by sergos — APPROVED** [review]

**Comment by CuriousGeorgiy** [comment]
> Yet the `m` for the `*arg` was an excess, since you had no access through the pointer.

But the function called in the inline assembly could access the agrument.

**Comment by CuriousGeorgiy** [comment]
> Yet the `m` for the `*arg` was an excess, since you had no access through the pointer.

@sergos But the function called in the inline assembly could access the agrument.

**Comment by locker** [comment]
Cherry-picked to 2.10.

**Pull request merged**
