### PR TITLE
lua: bump metrics module

### PR DESCRIPTION
**Pull request by DifferentialOrange**
Bump metrics package submodule. Commits from PRs [1-4] affect Tarantool, the other ones are related to module infrastructure.

1. https://github.com/tarantool/metrics/pull/482
2. https://github.com/tarantool/metrics/pull/483
3. https://github.com/tarantool/metrics/pull/484
4. https://github.com/tarantool/metrics/pull/491

NO_DOC=doc is a part of submodule

### CODE REVIEW

**Comment by DifferentialOrange** [comment]
CI fails due to https://github.com/tarantool/tarantool/issues/10143

**Review by Buristan — APPROVED** [review]
Hi, Georgy!
Thanks for the patch!
I see no flaws, but I concerned that jobs [1] [2] are red. Is it expected behaviour?

Also, I prefer to wait for green CI, i.e. that the #10143 is resolved.

[1]: https://github.com/tarantool/metrics/actions/runs/9855411429/job/27210242764
[2]: https://github.com/tarantool/metrics/actions/runs/9855421534/job/27210468985

**Comment by DifferentialOrange** [comment]
> Is it expected behaviour?

Yeah, "Pull translation" job is broken for a long time.

**Review by p7nov — APPROVED** [review]

**Review by Totktonada — APPROVED** [review]
I've no objections.

**Pull request merged**
