### PR TITLE
extendable authentication via on_auth trigger

### PR DESCRIPTION
**Pull request by parihaaraka**
```lua
box.session.on_auth(function(uname, is_ok, salt, scramble)
   if uname == 'test' then
      return 'super'
   end
end, box.session.on_auth()[1])
```
```bash
$ tarantoolctl connect bad_test:test@127.0.0.1:3301
User 'bad_test' is not found
$ tarantoolctl connect test:test@127.0.0.1:3301
connected to 127.0.0.1:3301
127.0.0.1:3301> box.session.user()
---
- super
...
```

### CODE REVIEW

**Comment by Mons** [comment]
There is a lack of a detailed description of the proposed feature.
From the pull I can't fully understand how it works. In the changes I can't find any doc or comments.
It has a possibility to be merged, but we need more verbose and detailed feature description and behavior

**Comment by parihaaraka** [comment]
The PR allows to utilize internal accounts as roles only (32(27) roles + unlimited number of users). 
* `get_scramble()` contains original code so it has all the comments being there before.
The idea is to try to authenticate **unknown** user by means of `on_auth` trigger and **map it to known** user or role. External users distinction proposed to be on an application side (e.g. within box.session.storage). Internal roles are to be used for authorization only.
The logic (I mistakenly believed my comments and example with the trigger's arguments are clear enough):
if the user being passed to `authenticate()` is unknown and the trigger handler exists, then call it with admin privileges (to have externals users storage access) and try to acquire target (existent internal) user/role name. If target user/role successfully acquired and exists, then assign it to current session for authorization only purposes.
Here are some snippets to test the subj:

```lua
do
    if box.space._extra_user ~= nil then
        return
    end
    box.schema.space.create(
        '_extra_user',
        {
            format = {
                -- прикладной пользователь, котрого не существует в спэйсе _user
                {'name', 'string'},
                -- реальная роль из спэйса _user для сессии этого пользователя
                {'role', 'string'},
                -- sha1(sha1("password"))
                {'hash2', 'string'},
                -- ручка для временного отключения
                {'enabled', 'boolean'},
                -- блокнотик
                {'description', 'string', is_nullable = true},
            }
        }
    ):create_index('pk', { type = 'hash', parts = {'name'} })

    box.schema.user.create('nobody')
    box.schema.user.grant('nobody', 'execute', 'universe') -- чтобы подключиться терминалом

    local d = require('digest')
    box.space._extra_user:insert({'test', 'super', d.sha1(d.sha1('qwerty')), true})
    box.space._extra_user:insert({'test2', 'nobody', d.sha1(d.sha1('qwe')), true})
end

box.session.on_auth(function(uname, is_ok, salt, scramble)
    local u = box.space._extra_user:get(uname)
    if u == nil then
        return
    elseif not u.enabled then
        box.error(box.error.NO_SUCH_USER, uname)
    end
    local d = require('digest')
    local s_hash = d.sha1(salt .. u.hash2)
    local hash1 = ''
    for i = 1, #s_hash do
        hash1 = hash1 .. string.char(bit.bxor(string.byte(scramble, i), string.byte(s_hash, i)))
    end
    local candidate_hash2 = d.sha1(hash1)
    if candidate_hash2 == u.hash2 then
        return u.role
    end
    box.error(box.error.PASSWORD_MISMATCH, uname)
end, box.session.on_auth()[1])
```

**Comment by kyukhin** [comment]
BTW, why do you intend to commit to 2.8?

**Comment by parihaaraka** [comment]
> BTW, why do you intend to commit to 2.8?

to have the subj in the latest stable build
`¯\_(ツ)_/¯`

**Comment by locker** [comment]
@parihaaraka Do I read correctly that the sole goal of this change is to circumvent the limit on the total number of registered users? Would you need this change if we increased the cap?

**Comment by parihaaraka** [comment]
> @parihaaraka Do I read correctly that the sole goal of this change is to circumvent the limit on the total number of registered users? Would you need this change if we increased the cap?

Never heard about it. May I have some more details?
*btw i've got some problems with assigning a role to a session. It looks like I need some more investigation to avoid extra user for each usable role :( In [this](https://github.com/tarantool/tarantool/pull/6673#issuecomment-988576395) environment i've got:
```
$ ./tntcall test3:qwe@127.0.0.1:3301 test
test ok
$ ./tntcall test2:qwe@127.0.0.1:3301 test
Execute access to function 'test' is denied for user 'nobody'
code 42
```

**Comment by locker** [comment]
> > @parihaaraka Do I read correctly that the sole goal of this change is to circumvent the limit on the total number of registered users? Would you need this change if we increased the cap?
> 
> Never heard about it. May I have some more details?

You wrote:

> The PR allows to utilize internal accounts as roles only (32(27) roles + unlimited number of users).

So I assume that you need this change, because the number of users/roles in Tarantool is limited by 32 (`BOX_USER_MAX`) so you can't create an internal account per user. If there wasn't such limit or the limit was high, would you still need this change?

In other words, I'm trying to figure out if this change is a workaround for a Tarantool limitation or it has a value on its own. I'm not sure we can easily raise the `BOX_USER_MAX` limit so even if it is a workaround it might still make sense. Anyway, it'd be nice if you could provide us with some use cases that might utilize this feature.

**Comment by parihaaraka** [comment]
@locker Yes, this change is just a workaround for a Tarantool limitation. We use tarantool as application server with multiple api bunches (=roles), 1+ internal services per role and multiple users (they must be uniquely identified and have app-level permissions).

**Comment by parihaaraka** [comment]
role usage resolved

**Comment by parihaaraka** [comment]
> @parihaaraka Do I read correctly that the sole goal of this change is to circumvent the limit on the total number of registered users? Would you need this change if we increased the cap?

This zero-cost change don't restrict you to increase the cap but it works right now. Not bad temporary solution to stay forever :)

**Comment by parihaaraka** [comment]
What are you talking about?! Is it ok to change every client to add another authentication call and then check it manually in every function??? The patch allows to use 27 ROLES (permission sets (excluding internal ones)) to **authorize** an unlimited number of users.

**Comment by locker** [comment]
> What are you talking about?! Is it ok to change every client to add another authentication call and then check it manually in every function??? The patch allows to use 27 ROLES (permission sets (excluding internal ones)) to authorize an unlimited number of users.

This kind of authorization would be pointless from Tarantool's point of view, because the "unlimited number of users" would be mapped to a single user/role by Tarantool and all credential checks (what a user can do) would have to be done by the application code anyways (as you mentioned yourself in one of your comments) or you'd just use the same access rights for all users mapping to the same user/role, but in that case there's no point to use different users at client side. If you implement access checks in your application code, you can as well add one more method for application-level authentication - a function that would be called by every client before issuing any requests. The fact that patching all clients might not be an option now isn't an excuse to add a workaround to the core code.

Anyways, I don't see a justification for the existing internal Tarantool limitation of 32 users - it looks like it just was the easy way to go. It should be fixable, and once it's fixed this workaround will become pointless. Feel free to file a ticket to remove the limitation (I haven't found one; looks like nobody's asked for this so far).

**Comment by parihaaraka** [comment]
This is not about Tarantool's point of view. We **may** identify a user if an application needs it. In most cases this is not the point - the main point is to authenticate user groups (27) by internal means. No need to modify every function, no need to execute custom authentication function. 27 roles is a **much** more usable limit than 27 accounts (useless at all).

**Comment by Mons** [comment]
1. I see nothing harmless to the Tarantool ecosystem from this PR.
2. I see useful scenarios from this PR. In the case we have no plans to raise the user_max limit this PR is useful.

Meanwhile tests, docs, and PR against master branch are expected. Features could not be merged into 2.8.

**Comment by alyapunov** [comment]
Let's make an imaginary experiment: if tarantool hadn't had a hard limit of 32 users, would this patch have been needed? I guess no.

My point is: if we want to solve the problem of hard user limit, we should solve it in different way, and we know how. Perhaps our fault it that we didn't prioritize this problem and haven't solve it yet.

It would be nice if we had a temporary workaround, but unfortunately this patch makes a permanent solution with some unresolvable drawbacks that we would have to support to the end of time. For example it exposes sha1 logic to lua and mixes old and new meanings of on_auth triggers. Look what we will have to support and explain (!) to users:
1. User is found, the pass is correct: triggers are run by **guest**, a trigger **can't** change user.
1. User is found, the pass is incorrect: triggers are run by **guest**, a trigger **can't** change user.
1. User was not found by name: triggers are run by **admin**, a trigger **can** change user.

On the other hand we already have workaround that @locker suggested.
My opinion is that we should take another path. Thanks nevertheless.

**Comment by parihaaraka** [comment]
Don't you think on_auth trigger should always be called by admin? I ought to prepare admin context before trigger call, because there is no way to use the trigger in the necessary way. 
Sha1 logic is not mandatory - that was just an example. A user may change authentication data semantic to process it in other way.
>new meanings of on_auth triggers

what did it mean before?

**Comment by alyapunov** [comment]
You can't avoid sha1 logic - you can't even get a password send by user - you only have scramble.

**Pull request closed without merging**
