### PR TITLE
test, datetime: get rid of datetime.result for unit test

### PR DESCRIPTION
**Pull request by tsafin**
Despite the fact that unit tests were generating (mostly) TAP compatible output
we still used result files to make them pass test-run. But those result files were 
redundant if output would be fully TAP compliant:

**TAP** (Test Anything Protocol) output must indicate that this is `TAP13` in the first line. 
See specification https://testanything.org/tap-version-13-specification.html
To comply this specification we introduce few changes to `unit.h` facilities (i.e. `plan()`, `header()`, `footer()`)
which generates strict TAP output.

Unfortunately direct changes to `unit.h` would require us massive changes everywhere. If we would change output;
- we have to update all result files;
- we have to change `CMakeLists.txt` to add dependency on `unit.c` where `_space()` function implemented;
- we have to modify big chunk of unit tests, as they do not call `plan()` at all, thus there is no chance to "automagically" output `TAP13` header.

So, to be able to modify only 1 particular test (e.g. datetime), and eventually be able to modify the rest in case-by-case fashion, we have used "plan B" strategy:
- we introduce new `tapunit.h` file, which is used only in the test we plan to migrate;
- `tapunit.h` is header-only (as amalgamation of former `unit.h` and `unit.c`) thus does not require any modification of `CMakeLists.txt`;
- at the end of this story (when all unit tests would be migrated to `tapunit.h`) we could get rid of dependency on `unit` library in cmake, dramatically simplifying it.

> As a 1st step we migrate from `unit.h` to `tapunit.h` only in `datetime.c` unit test, deleting corresponding result file.

Co-authored-by: @ligurio 

Followup to #5000, #6731

### CODE REVIEW

**Comment by Totktonada** [comment]
Can we descrease the diff (and code duplication) by introducing a macro to be defined before inclusion of `unit.h`? Kinda so:

```c
/* New test. */
#define UNIT_H_COMPAT_MODE 0
#include <unit.h>
```

```c
/* Old test. */
#include <unit.h>
```

**Comment by Totktonada** [comment]
(Please, re-request review after answers / fixes.)

**Comment by ligurio** [comment]
Discussion started in https://github.com/tarantool/tarantool/pull/6731/files#r784120138

**Comment by tsafin** [comment]
I've created pull-request for alternative implementation with define used and `unit.h` modifications #6815 . It has smaller diff for `unit.h` changes today (but will have IMHO uglier code once all unit tests will be migrated to `tapunit.h` of the current approach. Because `tapunit.h` is cleaner if we amalgamize all code to the single file without any conditional defines).

Please select the preferred way...
image

**Comment by tsafin** [comment]
We have selected alternative implementation #6815
Closing this pull-request.

**Pull request closed without merging**
