### PR TITLE
github-ci: add ubuntu hirsute (21.04) workflow

### PR DESCRIPTION
**Pull request by VitaliyaIoffe**
Add ubuntu-hirsute workflow, which runs on push and pull-requests.

Part of: #5825

### CODE REVIEW

**Comment by Totktonada** [comment]
I pushed https://github.com/packpack/packpack-docker-images/pull/77 and restarted the ubuntu_21_04 job here.

Please, apply my comments from https://github.com/tarantool/tarantool/pull/6100#issuecomment-854999242 here as well.

**Comment by VitaliyaIoffe** [comment]
Was rebased on [VitaliyaIoffe/gh-5824-add-ubuntu-groovy-release](https://github.com/tarantool/tarantool/pull/6100)

**Comment by Totktonada** [comment]
>  github-ci: add ubuntu hirsute (21.04) workflow
>
> Add ubuntu-hirsute workflow, which runs on push and pull-requests.
> Fix lintian globbing-patterns-out-of-order warnings.

The latter is fixed in one of previous commits.

**Review by Totktonada — APPROVED** [review]
LGTM.

Please, don't forget to rebase after PR #6100 push.

**Review by Gerold103 — APPROVED** [review]

**Review by kyukhin — APPROVED** [review]

**Pull request merged**
