### PR TITLE
Hide tarantool symbols back

### PR DESCRIPTION
**Pull request by LeonidVas**
This is a partial backport of the commit [1], which includes:
- adding sorting for "exports"
- fix a typo in "mkexports"

1. https://github.com/tarantool/tarantool/commit/5ceabb378d0169dc776449e45577515114e39f12

Part of #5932

### CODE REVIEW

**Review by Totktonada — APPROVED** [review]
I have no objections. I understand that it is for unification with master. However, as for me, even approximate categorization was better than 'a bag of symbols'.

Maybe it worth to adjust the commit title (we don't hide symbols there, right)?

**Comment by LeonidVas** [comment]
> I have no objections. I understand that it is for unification with master. However, as for me, even approximate categorization was better than 'a bag of symbols'.
> 

As for me, I agree with the comment:
Keep the symbols sorted by name for search and addition simplicity, to avoid duplicates. Makes no much sense to split them into any sections. Anyway some symbols will end-up belonging to several of them at once, and it would require moving lines here when a symbol goes from privately exported to the public C API.

> Maybe it worth to adjust the commit title (we don't hide symbols there, right)?

Yep, I preferred to keep the "original" commit title and explain what the commit actually does in the commit message.
I can replace it with `export: backport the commit "cmake: hide tarantool symbols back "`

**Comment by Totktonada** [comment]
My opinion is that the original commit title is just confusing, when you read 1.10 commits. It would be better to make the title correspond to the changes (this is the general principle) and mention the origin somewhere in the commit body. Up to you.

**Comment by LeonidVas** [comment]
> My opinion is that the original commit title is just confusing, when you read 1.10 commits. It would be better to make the title correspond to the changes (this is the general principle) and mention the origin somewhere in the commit body. Up to you.

Ok. I split the commit in two and updated the commit titles.

**Review by kyukhin — APPROVED** [review]

**Review by VitaliyaIoffe — APPROVED** [review]
QA LGTM

**Pull request merged**
